import {useMemo,useState} from "react";
import {openUrl} from "@tauri-apps/plugin-opener";
import type {AppSnapshot,ResearchCatalogItem,ResearchComponentKind} from "../../shared/contracts";
import {ItemHover} from "../items/ItemHover";
import {money} from "../ui";
import {buildResearchComponentInventory,buildResearchRecipes,type ResearchRecipeView} from "./model";
import "./spell-research.css";

const CLASSES=["Enchanter","Magician","Necromancer","Wizard"] as const;
const KINDS:["all"|ResearchComponentKind,string][]=[["all","All components"],["word","Words"],["page","Pages"],["rune","Runes"],["spell","Spell scrolls"],["other","Other items"]];
const icon=(id?:number)=>id?`/item-icons/Item_${id}.png`:undefined;

export function SpellResearchPage({data}:{data:AppSnapshot}){
 const[view,setView]=useState<"recipes"|"components">("recipes"),[className,setClassName]=useState("All classes"),[level,setLevel]=useState("All levels"),[kind,setKind]=useState<"all"|ResearchComponentKind>("all"),[filter,setFilter]=useState(""),[ownedOnly,setOwnedOnly]=useState(false),[readyOnly,setReadyOnly]=useState(false),[researchOnly,setResearchOnly]=useState(false),[expanded,setExpanded]=useState<Set<number>>(new Set());
 const recipes=useMemo(()=>buildResearchRecipes(data.researchCatalog,data.inventory),[data.researchCatalog,data.inventory]);
 const components=useMemo(()=>buildResearchComponentInventory(recipes),[recipes]);
 const levels=useMemo(()=>[...new Set(recipes.filter(row=>className==="All classes"||row.className===className).map(row=>row.level))].sort((a,b)=>a-b),[recipes,className]);
 const query=filter.trim().toLocaleLowerCase();
 const visibleRecipes=useMemo(()=>recipes.filter(recipe=>className==="All classes"||recipe.className===className).filter(recipe=>level==="All levels"||recipe.level===Number(level)).filter(recipe=>kind==="all"||recipe.components.some(component=>component.componentKind===kind)).filter(recipe=>!ownedOnly||recipe.ownedRequirements>0).filter(recipe=>!readyOnly||recipe.ready).filter(recipe=>!researchOnly||recipe.researchOnly).filter(recipe=>!query||[recipe.className,recipe.spellName,recipe.level,recipe.trivial,...recipe.components.flatMap(component=>[component.itemName,component.componentKind,...component.holders.map(holder=>holder.character)])].join(" ").toLocaleLowerCase().includes(query)),[recipes,className,level,kind,ownedOnly,readyOnly,researchOnly,query]);
 const visibleComponents=useMemo(()=>components.filter(component=>kind==="all"||component.kind===kind).filter(component=>!ownedOnly||component.held>0).filter(component=>className==="All classes"||component.recipes.some(recipe=>recipe.className===className)).filter(component=>level==="All levels"||component.recipes.some(recipe=>recipe.level===Number(level))).filter(component=>!researchOnly||component.recipes.some(recipe=>recipe.researchOnly)).filter(component=>!query||[component.itemName,component.kind,...component.holders.map(holder=>holder.character),...component.recipes.map(recipe=>`${recipe.className} ${recipe.spellName}`)].join(" ").toLocaleLowerCase().includes(query)),[components,kind,ownedOnly,className,level,researchOnly,query]);
 const ready=recipes.filter(recipe=>recipe.ready).length,heldTypes=components.filter(component=>component.held>0).length,totalHeld=components.reduce((sum,component)=>sum+component.held,0),heldValue=components.reduce((sum,component)=>sum+component.held*(component.valuePp||0),0);
 const groups=CLASSES.map(name=>({name,recipes:visibleRecipes.filter(recipe=>recipe.className===name)})).filter(group=>group.recipes.length);
 const reset=()=>{setClassName("All classes");setLevel("All levels");setKind("all");setFilter("");setOwnedOnly(false);setReadyOnly(false);setResearchOnly(false)};
 const allExpanded=visibleRecipes.length>0&&visibleRecipes.every(recipe=>expanded.has(recipe.recipeId));
 return <>
  <section className="research-stats"><article><span>Recipes ready</span><strong>{ready} / {recipes.length}</strong></article><article><span>Component types found</span><strong>{heldTypes} / {components.length}</strong></article><article><span>Total components held</span><strong>{totalHeld}</strong></article><article><span>Estimated held value</span><strong>{money(heldValue)}</strong></article></section>
  <section className="research-intro"><div><span className="eyebrow">Offline P99 research catalog</span><h2>Spell Research Workshop</h2><p>Track every word, page, rune, chained spell scroll, and supporting item across the entire roster.</p></div><button onClick={()=>openUrl("https://wiki.project1999.com/Research")}>P99 Research source ↗</button></section>
  <section className="research-view-switch"><button className={view==="recipes"?"active":""} onClick={()=>setView("recipes")}><strong>Recipe readiness</strong><small>What can the roster craft?</small></button><button className={view==="components"?"active":""} onClick={()=>setView("components")}><strong>Component inventory</strong><small>What should be kept?</small></button></section>
  <section className="research-toolbar">
   <label className="search"><input value={filter} onChange={event=>setFilter(event.target.value)} placeholder="Search spells, words, pages, runes, or characters..."/><button disabled={!filter} onClick={()=>setFilter("")} aria-label="Clear research filter">×</button></label>
   <select value={className} onChange={event=>{setClassName(event.target.value);setLevel("All levels")}} aria-label="Research class"><option>All classes</option>{CLASSES.map(name=><option key={name}>{name}</option>)}</select>
   <select value={level} onChange={event=>setLevel(event.target.value)} aria-label="Spell level"><option>All levels</option>{levels.map(value=><option key={value} value={value}>Level {value}</option>)}</select>
   <select value={kind} onChange={event=>setKind(event.target.value as typeof kind)} aria-label="Component type">{KINDS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>
   <label className="check-line"><input type="checkbox" checked={ownedOnly} onChange={event=>setOwnedOnly(event.target.checked)}/> Held only</label>
   {view==="recipes"&&<label className="check-line"><input type="checkbox" checked={readyOnly} onChange={event=>setReadyOnly(event.target.checked)}/> Ready only</label>}
   <label className="check-line"><input type="checkbox" checked={researchOnly} onChange={event=>setResearchOnly(event.target.checked)}/> Research-only</label>
   {view==="recipes"&&<button onClick={()=>setExpanded(allExpanded?new Set():new Set(visibleRecipes.map(recipe=>recipe.recipeId)))}>{allExpanded?"Collapse all":"Expand all"}</button>}
  </section>
  <div className="research-count">{view==="recipes"?`${visibleRecipes.length} recipes`:`${visibleComponents.length} component types`} match these filters</div>
  {view==="recipes"?<section className="research-groups">{groups.map(group=><section className="research-group" key={group.name}><header><div><span>Research class</span><h2>{group.name}</h2></div><small>{group.recipes.length} recipes · {group.recipes.filter(recipe=>recipe.ready).length} ready</small></header><div className="research-recipe-grid">{group.recipes.map(recipe=><RecipeCard key={recipe.recipeId} recipe={recipe} expanded={expanded.has(recipe.recipeId)} toggle={()=>setExpanded(current=>{const next=new Set(current);next.has(recipe.recipeId)?next.delete(recipe.recipeId):next.add(recipe.recipeId);return next})}/>)}</div></section>)}</section>:<section className="research-component-grid">{visibleComponents.map(component=><article className={component.held?"owned":"missing"} key={component.key}><ItemHover itemName={component.itemName} itemId={component.itemId} iconId={component.iconId} valuePp={component.valuePp}><span className="research-component-icon">{icon(component.iconId)?<img src={icon(component.iconId)} alt=""/>:<b>?</b>}</span></ItemHover><div><small>{component.kind} · used in {component.recipes.length} recipe{component.recipes.length===1?"":"s"}</small><strong>{component.itemName}</strong><em>{component.valuePp?`${money(component.valuePp)} each`:"No stored value"}</em></div><b>{component.held}</b>{component.holders.length?<details><summary>{component.holders.length} holder{component.holders.length===1?"":"s"}</summary>{component.holders.map(holder=><p key={holder.character}><strong>{holder.character}</strong><span>×{holder.count}</span><small>{holder.locations.join(", ")}</small></p>)}</details>:<span className="research-missing-label">Missing across roster</span>}<footer>{component.recipes.slice(0,4).map(recipe=><span key={recipe.recipeId}>{recipe.className.slice(0,3)} {recipe.level}: {recipe.spellName}</span>)}{component.recipes.length>4&&<span>+{component.recipes.length-4} more</span>}</footer></article>)}</section>}
  {((view==="recipes"&&!visibleRecipes.length)||(view==="components"&&!visibleComponents.length))&&<section className="research-empty"><strong>No research results match these filters.</strong><button onClick={reset}>Reset filters</button></section>}
 </>;
}

function RecipeCard({recipe,expanded,toggle}:{recipe:ResearchRecipeView;expanded:boolean;toggle:()=>void}){
 const progress=Math.round(recipe.ownedRequirements/Math.max(1,recipe.totalRequirements)*100);
 return <article className={`research-recipe ${recipe.ready?"ready":recipe.ownedRequirements?"started":"missing"}`}><header><button onClick={toggle} aria-expanded={expanded}><span className="research-spell-level">{recipe.level}</span><span><small>{recipe.researchOnly?"Research only":`Availability: ${recipe.availability}`}</small><strong>{recipe.spellName}</strong><em>Trivial {recipe.trivial} · {recipe.craftableCopies?`${recipe.craftableCopies} combine${recipe.craftableCopies===1?"":"s"} ready`:`${recipe.ownedRequirements} of ${recipe.totalRequirements} components ready`}</em></span></button><button title="Open P99 Research" aria-label="Open P99 Research" onClick={()=>openUrl(recipe.sourceUrl)}>Open</button></header><div className="research-progress"><i style={{width:`${progress}%`}}/><span>{progress}%</span></div><div className={`research-recipe-components ${expanded?"expanded":""}`}>{recipe.components.map(component=><article key={component.componentId} className={component.held>=component.quantity?"owned":"missing"}><ItemHover itemName={component.itemName} itemId={component.itemId} iconId={component.iconId} valuePp={component.valuePp}><span className="research-component-icon">{icon(component.iconId)?<img src={icon(component.iconId)} alt=""/>:<b>?</b>}</span></ItemHover><div><small>{component.componentKind}</small><strong>{component.itemName}</strong>{expanded&&<em>{component.valuePp?money(component.valuePp):"No stored value"}</em>}</div><b>{component.held} / {component.quantity}</b>{expanded&&component.holders.length>0&&<details><summary>{component.holders.length} holder{component.holders.length===1?"":"s"}</summary>{component.holders.map(holder=><p key={holder.character}><strong>{holder.character}</strong><span>×{holder.count}</span><small>{holder.locations.join(", ")}</small></p>)}</details>}</article>)}</div></article>;
}