import {useState} from "react";
import {getDotTrainingPreview} from "../../shared/backend";
import type {DotTrainingEncounter,DotTrainingEvent,DotTrainingLine,DotTrainingReport,ReplayFile} from "../../shared/contracts";
import {DataTable,type Column} from "../ui";
import {DotTrainingReplay} from "./DotTrainingReplay";
import {ReplayLibrary} from "./ReplayLibrary";
import {ProcCoachPanel} from "./ProcCoachPanel";
import {describeProcSpell,describeTrainingEventSource} from "./damageSources";

const SAMPLE=`[Sun Sep 06 10:52:59 2026] You begin casting Dawncall.
[Sun Sep 06 10:53:04 2026] Hexbone skeleton staggers as the light of dawn washes over it.
[Sun Sep 06 10:53:06 2026] You crush Hexbone skeleton for 79 points of damage.
[Sun Sep 06 10:53:10 2026] Legiteral crushes Hexbone skeleton for 81 points of damage.
[Sun Sep 06 10:53:25 2026] a mortiferous golem staggers as the light of dawn washes over it.
[Sun Sep 06 10:53:26 2026] Asquatii tries to crush a mortiferous golem, but a mortiferous golem ripostes!
[Sun Sep 06 10:53:27 2026] Judoku says 'Ahhh, I feel much better now\...'
[Sun Sep 06 10:53:27 2026] Hexbone skeleton staggers.
[Sun Sep 06 10:53:27 2026] Judoku crushes hexbone skeleton for 37 points of damage.`;
type Verdict="correct"|"wrong";
const parseTime=(value:string)=>{const parsed=Date.parse(value.includes("T")?value:value.replace(" ","T"));return Number.isFinite(parsed)?parsed:0};
const number=(value:number)=>Math.round(value).toLocaleString();

export function DotTrainingPage({activeCharacter}:{activeCharacter?:string}){
 const[text,setText]=useState(""),[character,setCharacter]=useState(activeCharacter||"Tester"),[project,setProject]=useState(true),[report,setReport]=useState<DotTrainingReport|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[feedback,setFeedback]=useState<Record<number,Verdict>>({}),[notes,setNotes]=useState(""),[replayPath,setReplayPath]=useState(""),[savedCoachReviews,setSavedCoachReviews]=useState(0);
 const analyze=async(sourceText=text,sourceCharacter=character,sourceProject=project)=>{setBusy(true);setError("");try{setReport(await getDotTrainingPreview(sourceText,sourceCharacter,sourceProject));setFeedback({})}catch(reason){setError(String(reason))}finally{setBusy(false)}};
 const loadReplay=async(replay:ReplayFile,path:string)=>{const replayText=replay.logLines.join("\n");setText(replayText);setCharacter(replay.activeCharacter);setProject(replay.projectAllTicks);setNotes(replay.notes||"");setReplayPath(path);setSavedCoachReviews(replay.coachReviews?.length||0);await analyze(replayText,replay.activeCharacter,replay.projectAllTicks)};
 const lineColumns:Column<DotTrainingLine>[]=[
  {key:"line",label:"Line",value:line=>line.lineNumber},{key:"time",label:"Time",value:line=>line.happenedAt||""},
  {key:"status",label:"Result",value:line=>line.status,render:line=><span className={`dot-lab-status ${line.status}`}>{line.status==="dot"?"DoT match":line.status==="proc"?"Proc confirmed":line.status}</span>},
  {key:"event",label:"Parser event",value:line=>line.parserEvent},
  {key:"interpretation",label:"Interpretation",value:line=>[line.summary,...line.decisions,line.rawLine].join(" "),render:line=><div className="dot-lab-interpretation"><strong>{line.summary}</strong>{line.decisions.map((decision,index)=><span key={index}>{decision}</span>)}<code>{line.rawLine}</code></div>},
 ];
 return <section className="dot-lab"><section className="dot-lab-editor card"><header><div><span className="eyebrow">Safe parser sandbox</span><h2>Proc &amp; DoT Training Lab</h2><p>Paste exact log lines to test the production parser without changing live combat history.</p></div><div className="button-row"><button onClick={()=>{setText(SAMPLE);setReport(null);setReplayPath("");setSavedCoachReviews(0)}}>Load example</button><button disabled={!text&&!report} onClick={()=>{setText("");setReport(null);setFeedback({});setNotes("");setError("");setReplayPath("");setSavedCoachReviews(0)}}>Clear</button><button className="primary" disabled={busy||!text.trim()} onClick={()=>analyze()}>{busy?"Analyzing...":"Analyze lines"}</button></div></header><div className="dot-lab-controls"><label><span>Active character</span><input value={character} onChange={event=>{setCharacter(event.target.value);setReplayPath("");setSavedCoachReviews(0)}} placeholder="Character represented by You"/></label><label className="check-line"><input type="checkbox" checked={project} onChange={event=>{setProject(event.target.checked);setReplayPath("");setSavedCoachReviews(0)}}/><span>Project recognized DoTs through expiration for the charts</span></label></div><textarea className="dot-lab-input" value={text} onChange={event=>{setText(event.target.value);setReplayPath("");setSavedCoachReviews(0)}} spellCheck={false} placeholder="Paste one or more complete [timestamp] EverQuest log lines here..."/>{error&&<div className="alert"><strong>Analysis failed</strong><span>{error}</span><button onClick={()=>setError("")}>x</button></div>}</section>
 <ReplayLibrary onLoad={loadReplay}/>
 {!report?<section className="dot-lab-empty"><strong>Ready for combat lines</strong><p>Results explain parser events, spell matches, target extraction, caster clues, refreshes, explicit-damage suppression, and inferred ticks.</p></section>:<><section className="dot-lab-stats"><article><span>Lines</span><strong>{report.lineCount}</strong><small>{report.recognizedCount} recognized</small></article><article><span>Combat profiles</span><strong>{number(report.combatProfileCount)}</strong><small>{number(report.dotProfileCount)} support calculated ticks</small></article><article><span>Encounters</span><strong>{report.encounters.length}</strong><small>{report.encounters.reduce((sum,row)=>sum+row.dots.length,0)} DoTs · {report.encounters.reduce((sum,row)=>sum+row.procs.length,0)} procs</small></article><article><span>Simulated damage</span><strong>{number(report.encounters.reduce((sum,row)=>sum+row.totalDamage,0))}</strong><small>{report.projectedAllTicks?"includes projected ticks":"through pasted time"}</small></article></section>
 {report.warnings.length>0&&<section className="dot-lab-warnings">{report.warnings.map((warning,index)=><p key={index}>{warning}</p>)}</section>}
 <ProcCoachPanel text={text} activeCharacter={character} projectAllTicks={project} report={report} replayPath={replayPath} loadedReviewCount={savedCoachReviews}/>
 <DotTrainingReplay report={report}/>
 <section className="dot-lab-results"><header><div><span className="eyebrow">Line-by-line decisions</span><h2>How the log was interpreted</h2><p>Use the review icons to keep track of decisions you want to confirm or correct.</p></div><strong>{Object.keys(feedback).length}/{report.lineCount} reviewed</strong></header><DataTable rows={report.lines} columns={lineColumns} rowKey={line=>line.lineNumber} empty="No lines were interpreted." actions={line=><><button className={feedback[line.lineNumber]==="correct"?"active good":""} aria-label={`Mark line ${line.lineNumber} correct`} title="Correct" onClick={()=>setFeedback(current=>({...current,[line.lineNumber]:"correct"}))}>✓</button><button className={feedback[line.lineNumber]==="wrong"?"active danger":""} aria-label={`Mark line ${line.lineNumber} incorrect`} title="Needs correction" onClick={()=>setFeedback(current=>({...current,[line.lineNumber]:"wrong"}))}>!</button></>}/></section>
 <section className="dot-lab-encounters">{report.encounters.map(encounter=><EncounterPreview key={encounter.id} encounter={encounter}/>)}{!report.encounters.length&&<div className="dot-lab-empty"><strong>No damage encounter generated</strong><p>A landing must match a cached Cast on Other profile or a standard damage line must identify a target.</p></div>}</section>
 <section className="dot-lab-feedback card"><header><div><h2>Review notes</h2><p>Record the intended spell, target, caster, timing, or refresh behavior while testing.</p></div><strong>{Object.values(feedback).filter(value=>value==="wrong").length} flagged</strong></header><textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Example: line 4 should attribute Dawncall to Asquatii because..."/></section></>}</section>;
}

function EncounterPreview({encounter}:{encounter:DotTrainingEncounter}){
 const columns:Column<DotTrainingEvent>[]=[{key:"time",label:"Time",value:event=>event.happenedAt},{key:"player",label:"Player",value:event=>event.attacker},{key:"attack",label:"Attack / Spell",value:event=>event.attack},{key:"likelySource",label:"Likely Source",value:event=>describeTrainingEventSource(encounter,event).label,render:event=>{const source=describeTrainingEventSource(encounter,event);return <span className={`damage-source ${source.confidence}`} title={source.evidence}>{source.label}</span>}},{key:"source",label:"Origin",value:event=>event.sourceKind,render:event=><span className={`dot-lab-status ${event.sourceKind==="explicit"?"recognized":event.sourceKind}`}>{event.sourceKind==="dot"?`DoT tick ${event.tickIndex}`:event.sourceKind==="proc"?"Inferred proc":"Explicit"}</span>},{key:"damage",label:"Damage",value:event=>event.damage,render:event=><strong>{number(event.damage)}</strong>}];
 const duration=Math.max(0,Math.round((parseTime(encounter.lastDamageAt)-parseTime(encounter.startedAt))/1000));
 return <article className="dot-lab-encounter card"><header><div><span className="eyebrow">Simulated encounter</span><h2>{encounter.mobName}</h2><p>{encounter.startedAt} - {duration}s - {encounter.outcome}</p></div><strong>{number(encounter.totalDamage)} damage</strong></header><div className="dot-lab-kpis"><div><span>Spell</span><strong>{number(encounter.spellDamage)}</strong></div><div><span>Melee</span><strong>{number(encounter.meleeDamage)}</strong></div><div><span>Events</span><strong>{encounter.hitCount}</strong></div><div><span>DoTs / Procs</span><strong>{encounter.dots.length} / {encounter.procs.length}</strong></div></div><div className="dot-lab-charts"><TrainingTimeline encounter={encounter}/><ParticipantBars encounter={encounter}/></div><section className="dot-lab-applications"><header><h3>DoT applications</h3><span>Refreshes never stack</span></header>{encounter.dots.map(dot=><article key={dot.id}><div><strong>{dot.spellName}</strong><small>{dot.casterName} -&gt; {dot.targetName}</small></div><dl><div><dt>Attribution</dt><dd>{dot.attributionMethod.replace("_"," ")}</dd></div><div><dt>Tick</dt><dd>{number(dot.damagePerTick)} / {dot.tickIntervalSeconds}s</dd></div><div><dt>Applied</dt><dd>{dot.ticksApplied} of {dot.totalTicks}</dd></div><div><dt>Status</dt><dd>{dot.status}{!dot.inferenceEnabled?" - inference disabled":""}</dd></div></dl></article>)}{!encounter.dots.length&&<p>No DoT landing was associated with this encounter.</p>}</section><section className="dot-lab-applications dot-lab-procs"><header><h3>Confirmed weapon procs</h3><span>Landing + immediately following same-target attack</span></header>{encounter.procs.map(proc=>{const source=describeProcSpell(proc.spellName,proc.directDamage,encounter.dots.some(dot=>dot.spellName.toLowerCase()===proc.spellName.toLowerCase()&&dot.attributionMethod==="proc")?1:0);return <article key={proc.id}><div><strong>{proc.spellName}</strong><small>{proc.casterName} -&gt; {proc.targetName}</small><em className={`damage-source ${source.confidence}`} title={source.evidence}>{source.label}</em></div><dl><div><dt>Direct damage</dt><dd>{number(proc.directDamage)}</dd></div><div><dt>Landing offset</dt><dd>{proc.landingSourceOffset}</dd></div><div><dt>Confirmed at</dt><dd>{proc.attributionSourceOffset}</dd></div><div><dt>Rule</dt><dd>attack-confirmed proc</dd></div></dl></article>})}{!encounter.procs.length&&<p>No attack-confirmed weapon proc was associated with this encounter.</p>}</section><DataTable rows={encounter.events} columns={columns} rowKey={event=>event.id} empty="No damage events generated."/></article>;
}

function ParticipantBars({encounter}:{encounter:DotTrainingEncounter}){const rows=[...encounter.participants].sort((a,b)=>b.totalDamage-a.totalDamage),max=Math.max(1,...rows.map(row=>row.totalDamage));return <section className="dot-lab-chart"><header><div><span className="eyebrow">Attribution result</span><h3>Damage by caster</h3></div></header><div className="damage-player-bars">{rows.map((row,index)=><div key={row.name}><b>{index+1}</b><span>{row.name}<small>{row.hitCount} events</small></span><i><em style={{width:`${row.totalDamage/max*100}%`}}/></i><strong>{number(row.totalDamage)}</strong></div>)}{!rows.length&&<p>No attributed damage.</p>}</div></section>}

function TrainingTimeline({encounter}:{encounter:DotTrainingEncounter}){const events=[...encounter.events].sort((a,b)=>parseTime(a.happenedAt)-parseTime(b.happenedAt)||a.id-b.id);if(!events.length)return <section className="dot-lab-chart"><header><h3>Cumulative damage</h3></header><div className="dot-lab-chart-empty">No damage points</div></section>;const width=720,height=210,left=48,right=14,top=16,bottom=28,pw=width-left-right,ph=height-top-bottom,start=parseTime(encounter.startedAt),end=Math.max(1,(parseTime(encounter.lastDamageAt)-start)/1000),max=Math.max(1,encounter.totalDamage);let cumulative=0;const points=events.map(event=>{cumulative+=event.damage;const second=Math.max(0,(parseTime(event.happenedAt)-start)/1000);return{event,second,x:left+Math.min(end,second)/end*pw,y:top+ph-cumulative/max*ph,total:cumulative}}),line=[`${left},${top+ph}`,...points.map(point=>`${point.x},${point.y}`)].join(" ");return <section className="dot-lab-chart"><header><div><span className="eyebrow">Combat preview</span><h3>Cumulative damage</h3></div><span>DoTs are ringed</span></header><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Cumulative damage against ${encounter.mobName}`}>{[0,.25,.5,.75,1].map(value=>{const y=top+ph*(1-value);return <g key={value}><line x1={left} x2={width-right} y1={y} y2={y}/><text x={left-6} y={y+3} textAnchor="end">{number(max*value)}</text></g>})}<polygon points={`${line} ${left+pw},${top+ph}`}/><polyline points={line}/>{points.map(point=><circle key={point.event.id} className={point.event.sourceKind} cx={point.x} cy={point.y} r={point.event.inferred?4:3}><title>+{Math.round(point.second)}s {point.event.attack}: {point.event.damage}; {point.total} cumulative</title></circle>)}<text x={left} y={height-8}>0s</text><text x={width-right} y={height-8} textAnchor="end">{Math.round(end)}s</text></svg></section>}