import {useEffect,useMemo,useState} from "react";
import {analyzeWithProcCoach,deleteProcCoachApiKey,getProcCoachStatus,saveProcCoachApiKey,saveReplayCoachReview} from "../../shared/backend";
import type {DotTrainingReport,ProcCoachFindingDecision,ProcCoachReview,ProcCoachSourceKind,ProcCoachStatus} from "../../shared/contracts";

type Draft=Omit<ProcCoachFindingDecision,"verdict">&{verdict:""|"accepted"|"rejected"};
const SOURCE_OPTIONS:{value:ProcCoachSourceKind;label:string}[]=[
 {value:"proc",label:"Weapon proc"},{value:"direct_cast",label:"Direct cast"},{value:"item_click",label:"Item click"},
 {value:"unattributed_spell",label:"Unattributed spell"},{value:"not_a_proc",label:"Not a proc"},
];
const displaySource=(value:ProcCoachSourceKind)=>SOURCE_OPTIONS.find(option=>option.value===value)?.label||value;

export function ProcCoachPanel({text,activeCharacter,projectAllTicks,report,replayPath,loadedReviewCount=0}:{text:string;activeCharacter:string;projectAllTicks:boolean;report:DotTrainingReport;replayPath:string;loadedReviewCount?:number}){
 const[status,setStatus]=useState<ProcCoachStatus|null>(null),[apiKey,setApiKey]=useState(""),[editingKey,setEditingKey]=useState(false);
 const[review,setReview]=useState<ProcCoachReview|null>(null),[drafts,setDrafts]=useState<Record<string,Draft>>({});
 const[busy,setBusy]=useState<""|"key"|"analyze"|"save">(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{let live=true;getProcCoachStatus().then(value=>{if(live)setStatus(value)}).catch(reason=>{if(live)setError(String(reason))});return()=>{live=false}},[]);
 useEffect(()=>{setReview(null);setDrafts({});setNotice("")},[report]);
 const decided=useMemo(()=>Object.values(drafts).filter(draft=>draft.verdict),[drafts]);
 const saveKey=async()=>{setBusy("key");setError("");try{setStatus(await saveProcCoachApiKey(apiKey));setApiKey("");setEditingKey(false);setNotice("API key saved securely.")}catch(reason){setError(String(reason))}finally{setBusy("")}};
 const removeKey=async()=>{setBusy("key");setError("");try{setStatus(await deleteProcCoachApiKey());setReview(null);setDrafts({});setNotice("Stored API key removed.")}catch(reason){setError(String(reason))}finally{setBusy("")}};
 const analyze=async()=>{setBusy("analyze");setError("");setNotice("");try{const next=await analyzeWithProcCoach(text,activeCharacter,projectAllTicks);setReview(next);setDrafts(Object.fromEntries(next.findings.map(finding=>[finding.id,{findingId:finding.id,verdict:"",sourceKind:finding.sourceKind,casterName:finding.probableCaster,spellName:finding.spellName,note:""}])))}catch(reason){setError(String(reason))}finally{setBusy("")}};
 const update=(id:string,patch:Partial<Draft>)=>setDrafts(current=>({...current,[id]:{...current[id],...patch}}));
 const persist=async()=>{if(!review||!replayPath||!decided.length)return;setBusy("save");setError("");try{await saveReplayCoachReview(replayPath,{reviewedAt:new Date().toISOString(),model:review.model,agentSummary:review.summary,findings:review.findings,decisions:decided as ProcCoachFindingDecision[]});setNotice(`Saved ${decided.length} reviewed finding${decided.length===1?"":"s"} to the replay file.`)}catch(reason){setError(String(reason))}finally{setBusy("")}};
 const keyEditor=!status?.configured||editingKey;
 return <section className="proc-coach card">
  <header><div><span className="eyebrow">Optional supervised review</span><h2>Proc Coach</h2><p>Compare the deterministic parser with a second opinion. The coach can suggest corrections, but never changes live parsing automatically.</p></div><div className="proc-coach-state"><span className={status?.configured?"ready":"needs-key"}>{status?.configured?"Ready":"API key needed"}</span>{loadedReviewCount>0&&<small>{loadedReviewCount} saved review{loadedReviewCount===1?"":"s"}</small>}</div></header>
  <div className="proc-coach-security"><div><strong>Private, explicit analysis</strong><p>Your key is kept in the {status?.secureStore||"operating-system credential vault"}. Exact pasted lines go to OpenAI only when you click Analyze with Agent, with response storage disabled.</p></div>{keyEditor?<div className="proc-coach-key"><input type="password" autoComplete="off" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder="OpenAI API key" aria-label="OpenAI API key"/><button disabled={busy==="key"||apiKey.trim().length<20} onClick={saveKey}>{busy==="key"?"Saving...":"Save securely"}</button>{status?.configured&&<button onClick={()=>{setEditingKey(false);setApiKey("")}}>Cancel</button>}</div>:<div className="button-row"><button onClick={()=>setEditingKey(true)}>Replace key</button><button className="danger" disabled={busy==="key"} onClick={removeKey}>Remove key</button></div>}</div>
  <div className="proc-coach-actions"><div><strong>{status?.model||"gpt-5.4-mini"}</strong><span>Suggest-only; every accepted correction remains under your control.</span></div><button className="primary" disabled={!status?.configured||busy==="analyze"||!text.trim()} onClick={analyze}>{busy==="analyze"?"Reviewing fight...":"Analyze with Agent"}</button></div>
  {error&&<div className="alert"><strong>Proc Coach needs attention</strong><span>{error}</span><button onClick={()=>setError("")}>x</button></div>}
  {notice&&<div className="alert success"><span>{notice}</span><button onClick={()=>setNotice("")}>x</button></div>}
  {review&&<div className="proc-coach-review"><header><div><span className="eyebrow">Agent review</span><h3>{review.findings.length} finding{review.findings.length===1?"":"s"}</h3><p>{review.summary}</p></div><span>{decided.length}/{review.findings.length} decided</span></header>
   <div className="proc-coach-findings">{review.findings.map(finding=>{const draft=drafts[finding.id];return <article key={finding.id} className={draft?.verdict||"pending"}><header><div><strong>{finding.spellName||displaySource(finding.sourceKind)}</strong><span>Lines {finding.lineNumbers.join(", ")} · {finding.confidence} confidence · parser {finding.parserVerdict}</span></div>{finding.suggestedDamage!==null&&<b>{finding.suggestedDamage.toLocaleString()} damage</b>}</header><p>{finding.explanation}</p>{finding.evidence.length>0&&<ul>{finding.evidence.map((evidence,index)=><li key={index}>{evidence}</li>)}</ul>}{finding.proposedCorrection&&<div className="proc-coach-correction"><strong>Suggested correction</strong><span>{finding.proposedCorrection}</span></div>}<div className="proc-coach-fields"><label><span>Classification</span><select value={draft?.sourceKind||finding.sourceKind} onChange={event=>update(finding.id,{sourceKind:event.target.value as ProcCoachSourceKind})}>{SOURCE_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><span>Caster</span><input value={draft?.casterName||""} onChange={event=>update(finding.id,{casterName:event.target.value||null})} placeholder="Unknown"/></label><label><span>Spell</span><input value={draft?.spellName||""} onChange={event=>update(finding.id,{spellName:event.target.value||null})} placeholder="Unknown"/></label><label className="wide"><span>Your note</span><input value={draft?.note||""} onChange={event=>update(finding.id,{note:event.target.value})} placeholder="Why this decision is correct or wrong"/></label></div><footer><button className={draft?.verdict==="accepted"?"active good":""} onClick={()=>update(finding.id,{verdict:"accepted"})}>Accept</button><button className={draft?.verdict==="rejected"?"active danger":""} onClick={()=>update(finding.id,{verdict:"rejected"})}>Reject</button></footer></article>})}{!review.findings.length&&<div className="proc-coach-empty">No questionable proc or spell attribution was found.</div>}</div>
   <footer><div>{replayPath?<span>Approved feedback will be appended to this external replay file.</span>:<span>Load a saved replay to persist reviewed findings for future training.</span>}</div><button className="primary" disabled={!replayPath||!decided.length||busy==="save"} onClick={persist}>{busy==="save"?"Saving feedback...":"Save reviewed feedback"}</button></footer>
  </div>}
 </section>;
}
