#!/usr/bin/env python3
"""Generate the offline P99 race/class starting-stat table used by the DPS calculator."""

from __future__ import annotations

import json
import re
import ssl
import tempfile
import time
import urllib.parse
import urllib.request
from pathlib import Path

API = "https://wiki.project1999.com/api.php"
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "app" / "dps-calculator" / "startingStats.generated.ts"
CLASSES = (
    "Bard", "Cleric", "Druid", "Enchanter", "Magician", "Monk", "Necromancer",
    "Paladin", "Ranger", "Rogue", "Shadow Knight", "Shaman", "Warrior", "Wizard",
)
STAT_KEYS = ("strength", "stamina", "agility", "dexterity", "wisdom", "intelligence", "charisma", "bonusPoints")


def source(title: str) -> str:
    cache = Path(tempfile.gettempdir()) / "eq-loot-tracker-p99-starting-stats" / f"{title.replace(' ', '_')}.txt"
    cache.parent.mkdir(exist_ok=True)
    if cache.exists():
        return cache.read_text(encoding="utf-8")
    query = urllib.parse.urlencode({"action": "parse", "page": title, "prop": "wikitext", "format": "json"})
    request = urllib.request.Request(f"{API}?{query}", headers={"User-Agent": "EverQuestLootTracker/3 starting-stat catalog"})
    last_error = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, context=ssl._create_unverified_context(), timeout=90) as response:
                value = json.load(response)["parse"]["wikitext"]["*"]
            cache.write_text(value, encoding="utf-8")
            return value
        except Exception as error:
            last_error = error
            time.sleep(attempt + 1)
    raise RuntimeError(f"{title}: wiki request failed: {last_error}")


def clean(value: str) -> str:
    value = re.sub(r"<!--.*?-->", "", value, flags=re.DOTALL)
    value = re.sub(r"\[\[(?:[^]|]+\|)?([^]]+)\]\]", r"\1", value)
    value = re.sub(r"\{\{[^{}]*\}\}", "", value)
    return re.sub(r"<[^>]+>|'''?|&nbsp;", "", value).strip()


def starting_rows(class_name: str) -> list[dict[str, object]]:
    text = source(class_name)
    header = re.search(r"!\s*Race\s*!!\s*Str\s*!!\s*Sta\s*!!\s*Agi\s*!!\s*Dex\s*!!\s*Wis\s*!!\s*Int\s*!!\s*Cha", text, flags=re.IGNORECASE)
    if not header:
        raise RuntimeError(f"{class_name}: starting-stat table not found")
    start = text.rfind("{|", 0, header.start())
    end = text.find("|}", header.end())
    section = text[start:end]
    header_line = text[header.start():text.find("\n", header.start())]
    labels = [value.strip().lower() for value in header_line.lstrip("!").split("!!")]
    bonus_index = labels.index("bonus") - 1 if "bonus" in labels else None
    rows: list[dict[str, object]] = []
    for block in re.split(r"^\|-.*$", section, flags=re.MULTILINE):
        cells = [clean(cell) for cell in re.split(r"\|\||\n\s*\|", block) if clean(cell)]
        numeric = [int(value) for value in cells[1:] if re.fullmatch(r"-?\d+", value)]
        race = re.sub(r"^.*\|\s*", "", cells[0]) if cells else ""
        if race.lower() == "race" or len(numeric) < 7:
            continue
        bonus = numeric[bonus_index] if bonus_index is not None and bonus_index < len(numeric) else 30
        rows.append({"race": race.replace("Half-Elf", "Half Elf"), "characterClass": class_name, **dict(zip(STAT_KEYS, [*numeric[:7], bonus]))})
    if not rows:
        raise RuntimeError(f"{class_name}: no starting-stat rows parsed")
    return rows


def main() -> None:
    rows = [row for class_name in CLASSES for row in starting_rows(class_name)]
    keys = {(row["race"], row["characterClass"]) for row in rows}
    if len(keys) != len(rows) or {row["characterClass"] for row in rows} != set(CLASSES):
        raise RuntimeError("Generated starting-stat table failed completeness checks")
    body = json.dumps(rows, indent=2, ensure_ascii=False).replace('"', "'")
    output = """// Generated by tools/scrape_starting_stats.py from P99 class Starting Statistics tables.
// Runtime use is entirely offline; regenerate deliberately and review the diff.
import type {StartingStats} from './startingStats';

export const GENERATED_STARTING_STATS:readonly StartingStats[]=""" + body + " as const;\n"
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {len(rows)} race/class rows to {OUTPUT}")


if __name__ == "__main__":
    main()
