ALTER TABLE loot_drops ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE loot_drops SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=loot_drops.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_loot_drops_item_id ON loot_drops(item_id);
CREATE TRIGGER IF NOT EXISTS trg_loot_drops_resolve_item_insert AFTER INSERT ON loot_drops WHEN NEW.item_id IS NULL BEGIN UPDATE loot_drops SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_loot_drops_resolve_item_update AFTER UPDATE OF item_name ON loot_drops BEGIN UPDATE loot_drops SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
ALTER TABLE tracked_loot_items ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE tracked_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=tracked_loot_items.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_tracked_loot_items_item_id ON tracked_loot_items(item_id);
CREATE TRIGGER IF NOT EXISTS trg_tracked_loot_items_resolve_item_insert AFTER INSERT ON tracked_loot_items WHEN NEW.item_id IS NULL BEGIN UPDATE tracked_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_tracked_loot_items_resolve_item_update AFTER UPDATE OF item_name ON tracked_loot_items BEGIN UPDATE tracked_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
ALTER TABLE manual_split_list_items ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE manual_split_list_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=manual_split_list_items.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_manual_split_list_items_item_id ON manual_split_list_items(item_id);
CREATE TRIGGER IF NOT EXISTS trg_manual_split_list_items_resolve_item_insert AFTER INSERT ON manual_split_list_items WHEN NEW.item_id IS NULL BEGIN UPDATE manual_split_list_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_manual_split_list_items_resolve_item_update AFTER UPDATE OF item_name ON manual_split_list_items BEGIN UPDATE manual_split_list_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
ALTER TABLE split_loot_items ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE split_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=split_loot_items.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_split_loot_items_item_id ON split_loot_items(item_id);
CREATE TRIGGER IF NOT EXISTS trg_split_loot_items_resolve_item_insert AFTER INSERT ON split_loot_items WHEN NEW.item_id IS NULL BEGIN UPDATE split_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_split_loot_items_resolve_item_update AFTER UPDATE OF item_name ON split_loot_items BEGIN UPDATE split_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
ALTER TABLE completed_split_items ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE completed_split_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=completed_split_items.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_completed_split_items_item_id ON completed_split_items(item_id);
CREATE TRIGGER IF NOT EXISTS trg_completed_split_items_resolve_item_insert AFTER INSERT ON completed_split_items WHEN NEW.item_id IS NULL BEGIN UPDATE completed_split_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_completed_split_items_resolve_item_update AFTER UPDATE OF item_name ON completed_split_items BEGIN UPDATE completed_split_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
ALTER TABLE activity_loot_history ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE activity_loot_history SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=activity_loot_history.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_activity_loot_history_item_id ON activity_loot_history(item_id);
CREATE TRIGGER IF NOT EXISTS trg_activity_loot_history_resolve_item_insert AFTER INSERT ON activity_loot_history WHEN NEW.item_id IS NULL BEGIN UPDATE activity_loot_history SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_activity_loot_history_resolve_item_update AFTER UPDATE OF item_name ON activity_loot_history BEGIN UPDATE activity_loot_history SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
ALTER TABLE activity_offer_history ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE activity_offer_history SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=activity_offer_history.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_activity_offer_history_item_id ON activity_offer_history(item_id);
CREATE TRIGGER IF NOT EXISTS trg_activity_offer_history_resolve_item_insert AFTER INSERT ON activity_offer_history WHEN NEW.item_id IS NULL BEGIN UPDATE activity_offer_history SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_activity_offer_history_resolve_item_update AFTER UPDATE OF item_name ON activity_offer_history BEGIN UPDATE activity_offer_history SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
ALTER TABLE linked_loot_items ADD COLUMN item_id INTEGER REFERENCES master_items(item_id) ON DELETE SET NULL;
UPDATE linked_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=linked_loot_items.item_name COLLATE NOCASE) WHERE item_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_linked_loot_items_item_id ON linked_loot_items(item_id);
CREATE TRIGGER IF NOT EXISTS trg_linked_loot_items_resolve_item_insert AFTER INSERT ON linked_loot_items WHEN NEW.item_id IS NULL BEGIN UPDATE linked_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
CREATE TRIGGER IF NOT EXISTS trg_linked_loot_items_resolve_item_update AFTER UPDATE OF item_name ON linked_loot_items BEGIN UPDATE linked_loot_items SET item_id=(SELECT item_id FROM item_name_resolutions WHERE item_name=NEW.item_name COLLATE NOCASE) WHERE id=NEW.id; END;
INSERT OR IGNORE INTO schema_migrations(version,name) VALUES(24,'canonical item ids across features');
